config:
  experiment_name: "sunnyday2snowynight-v2"
  init_img: "This one won't be used, as we are using the images from one folder."
  ddim_steps: 999 # we use 999 steps for the best reconstruction
  save_feature_timesteps: 50 # save 50 features, interval = 1000/50 ==20