config:
  experiment_name: "sunnyday2rainynight-v2-200-ddim"
  init_img: "This one won't be used, as we are using the images from one folder."
  ddim_inversion_steps: 200 # better use 999 steps for the best reconstruction
  ddim_steps: 200 # we use 999 steps for the best reconstruction
  save_feature_timesteps: 50 # save 50 features, interval = 1000/50 ==20
  source_weather: "sunny-day"
  target_weather: "rainy-night"

  scale: 5.0 # unconditional guidance scale. Note that a higher value encourages deviation from the source image
  num_ddim_sampling_steps: 50 # same with save_feature_timesteps
  # Control the level of structure preservation with injection timestep threshold
  feature_injection_threshold: 40 # should be in [0, num_ddim_sampling_steps]

  # Control the level of deviation from the source image with Negative prompting params.
  negative_prompt: "sunny day"
  negative_prompt_alpha: 1.0 # ∈ [0, 1], determines the initial strength of negative-prompting (lower = stronger)
  negative_prompt_schedule: "linear" # ∈ {"linear", "constant", "exp"}, determines the attenuation schedule of negative-prompting
  # setting negative_prompt_alpha = 1.0, negative_prompt_schedule = "constant" is equivalent to not using negative prompting
