config:
  experiment_name: "sunnyday2snowynight-v1-999-ddim"
  input_folder: "/home/turing/cfs_cz/finn/codes/DrivingEdition/examples/text_to_image/data/jidu-data-III-sensors/jidu-III-sunnyday2snowynight-v1/"
  ckpt: "models/ldm/stable-diffusion-v1/jidu_III_sunnyd2snowyn_v1_bs_6_lr_1e6_3000.ckpt"
  ddim_inversion_steps: 999
  ddim_steps: 999
  save_feature_timesteps: 200
  source_weather: "sunny-day"
  target_weather: "snowy-night"

  scale: 7.5
  num_ddim_sampling_steps: 200
  feature_injection_threshold: 160

  negative_prompt: "sunny day;delusion;moon;star"
  negative_prompt_alpha: 1.0
  negative_prompt_schedule: "linear"